# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kiroku < Formula
  desc "a minimal TUI task manager with spaces, two-column layout, and local persistence."
  homepage "https://github.com/kenanbendz/kiroku"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kenanbendz/kiroku/releases/download/v0.1.1/kiroku_0.1.1_darwin_amd64.tar.gz"
      sha256 "b90ea299033830cd6b32df42a4cf95533fbf7bd0563eac114f1c2791524f6cce"

      def install
        bin.install "kiroku"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kenanbendz/kiroku/releases/download/v0.1.1/kiroku_0.1.1_darwin_arm64.tar.gz"
      sha256 "5e8118c1ae1972de4124ef942bdc2aec23041d0a44b867cd99ac2c81318ac011"

      def install
        bin.install "kiroku"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kenanbendz/kiroku/releases/download/v0.1.1/kiroku_0.1.1_linux_amd64.tar.gz"
      sha256 "640e59d18063320d6f955395c6ffe9c761cbd8e04732b99d1de0e261b210f6d8"
      def install
        bin.install "kiroku"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kenanbendz/kiroku/releases/download/v0.1.1/kiroku_0.1.1_linux_arm64.tar.gz"
      sha256 "fa4af96a6d18bc0b40570b2dbb7454733028188c288131d5b9d188cb14cbfacd"
      def install
        bin.install "kiroku"
      end
    end
  end
end
