# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kiroku < Formula
  desc "a minimal TUI task manager with spaces, two-column layout, and local persistence."
  homepage "https://github.com/kenanbendz/kiroku"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kenanbendz/kiroku/releases/download/v0.1.0/kiroku_0.1.0_darwin_amd64.tar.gz"
      sha256 "da088de0a8fb3eb9b72a2720c20cf83d05453d4db7dc8c59159ef7e949f6f04d"

      def install
        bin.install "kiroku"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kenanbendz/kiroku/releases/download/v0.1.0/kiroku_0.1.0_darwin_arm64.tar.gz"
      sha256 "ed7851eb65d5c567192465bf990b0ce200cc387b701e4380f2ea3cadb6e34a79"

      def install
        bin.install "kiroku"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kenanbendz/kiroku/releases/download/v0.1.0/kiroku_0.1.0_linux_amd64.tar.gz"
      sha256 "85343acab0c3e257ab61e192ea305c011eb6546879dbf92d6a3d7bb898dd324e"
      def install
        bin.install "kiroku"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kenanbendz/kiroku/releases/download/v0.1.0/kiroku_0.1.0_linux_arm64.tar.gz"
      sha256 "b700956e1f1ef5e28f03ba9c0a1f6690f5e214d384da530ada92cd6d377f7ee3"
      def install
        bin.install "kiroku"
      end
    end
  end
end
