# This file was generated by GoReleaser. DO NOT EDIT.
cask "kiroku" do
  name "kiroku"
  desc "a minimal TUI task manager with spaces, two-column layout, and local persistence."
  homepage "https://github.com/kenanbendz/kiroku"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kiroku"

  on_macos do
    on_intel do
      url "https://github.com/kenanbendz/kiroku/releases/download/v#{version}/kiroku_#{version}_darwin_amd64.tar.gz"
      sha256 "f42453d8bbf89418cafe4fd6e1168c353c8b7e45ed1cb50853ad9ea50b0662f2"
    end
    on_arm do
      url "https://github.com/kenanbendz/kiroku/releases/download/v#{version}/kiroku_#{version}_darwin_arm64.tar.gz"
      sha256 "630863e5c7669d4316b0026dcf4fd092570e47352e04e5868dd4b73c03e826e7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kenanbendz/kiroku/releases/download/v#{version}/kiroku_#{version}_linux_amd64.tar.gz"
      sha256 "75d2fb77e4a4e909a9a7597bb3e2886ffc650924b0c36545fda2198dab407487"
    end
    on_arm do
      url "https://github.com/kenanbendz/kiroku/releases/download/v#{version}/kiroku_#{version}_linux_arm64.tar.gz"
      sha256 "8b7f653d8acfcef064747d0bc6e22538554803b888eadc74e0c9b6fac349e3ee"
    end
  end

  # No zap stanza required
end
